### ISSUE TITLE
Implement Places Autocomplete

### ISSUE THREAD

**Issue by ogbanana** [commsq/commsq-frontend#5]
When a resident types in the search bar, places autocomplete will suggest address base on their input. 
By default the suggestions are accessible by click.
- Make the suggestions accessible by the up and down arrow key.
- Allow the enter key to act the same way as click.

**Comment by mallockey** [comment]
Arrow keys and mouse hover allow the user to navigate through the list of suggestions. Enter key is the same onClick. Will need to change this so it doesn't make push to firebase but will do that in another ticket since its unrelated.
